package com.lapauseclub.manager.core;

import android.content.ContentValues;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;

import org.json.JSONArray;
import org.json.JSONObject;

final class CoreOwnerSchemaP3 {
    private CoreOwnerSchemaP3() {}
    static void create(SQLiteDatabase db){
        db.execSQL("CREATE TABLE IF NOT EXISTS security_roles_p3 (id TEXT PRIMARY KEY NOT NULL,name TEXT NOT NULL,permissions_json TEXT NOT NULL,system_role INTEGER NOT NULL DEFAULT 0,raw_json TEXT NOT NULL)");
        db.execSQL("CREATE TABLE IF NOT EXISTS audit_chain_p3 (id TEXT PRIMARY KEY NOT NULL,at_ms INTEGER NOT NULL,actor_id TEXT,actor_role TEXT,action TEXT NOT NULL,target TEXT,detail TEXT,severity TEXT NOT NULL,prev_hash TEXT NOT NULL,hash TEXT NOT NULL,meta_json TEXT NOT NULL)");
        db.execSQL("CREATE INDEX IF NOT EXISTS idx_audit_chain_p3_at ON audit_chain_p3(at_ms DESC)");
        db.execSQL("CREATE TABLE IF NOT EXISTS suspicious_events_p3 (id TEXT PRIMARY KEY NOT NULL,event_type TEXT NOT NULL,severity TEXT NOT NULL,summary TEXT NOT NULL,ref_id TEXT,evidence_json TEXT NOT NULL,status TEXT NOT NULL,created_at_ms INTEGER NOT NULL,resolved_at_ms INTEGER,resolution TEXT,raw_json TEXT NOT NULL)");
        db.execSQL("CREATE INDEX IF NOT EXISTS idx_suspicious_p3_status ON suspicious_events_p3(status,severity)");
        db.execSQL("CREATE TABLE IF NOT EXISTS owner_briefs_p3 (id TEXT PRIMARY KEY NOT NULL,business_day TEXT NOT NULL,generated_at_ms INTEGER NOT NULL,health_score INTEGER NOT NULL,revenue_minor INTEGER NOT NULL,sessions INTEGER NOT NULL,occupancy INTEGER NOT NULL,lost_revenue_minor INTEGER NOT NULL,forecast_minor INTEGER NOT NULL,forecast_confidence REAL NOT NULL,raw_json TEXT NOT NULL)");
        db.execSQL("CREATE TABLE IF NOT EXISTS next_best_actions_p3 (id TEXT PRIMARY KEY NOT NULL,category TEXT NOT NULL,title TEXT NOT NULL,why TEXT,estimated_impact TEXT,status TEXT NOT NULL,generated_at_ms INTEGER NOT NULL,raw_json TEXT NOT NULL)");
        db.execSQL("CREATE TABLE IF NOT EXISTS forecasts_p3 (id TEXT PRIMARY KEY NOT NULL,metric TEXT NOT NULL,model TEXT NOT NULL,predicted_minor INTEGER NOT NULL,confidence REAL NOT NULL,generated_at_ms INTEGER NOT NULL,horizon_days INTEGER NOT NULL,actual_minor INTEGER,error_minor INTEGER,raw_json TEXT NOT NULL)");
        db.execSQL("CREATE TABLE IF NOT EXISTS revenue_experiments_p3 (id TEXT PRIMARY KEY NOT NULL,name TEXT,status TEXT NOT NULL,hypothesis TEXT,started_at_ms INTEGER,ended_at_ms INTEGER,baseline_json TEXT,result_json TEXT,raw_json TEXT NOT NULL)");
    }
    static void dualWrite(SQLiteDatabase db,JSONObject root,long revision,long now){
        upsertRoles(db,root.optJSONArray("securityRoles"));upsertAudit(db,root.optJSONArray("auditChain"));upsertSuspicious(db,root.optJSONArray("suspiciousEvents"),now);upsertBriefs(db,root.optJSONArray("ownerBriefs"),now);upsertActions(db,root.optJSONArray("nextBestActions"),now);upsertForecasts(db,root.optJSONArray("forecasts"),now);upsertExperiments(db,root.optJSONArray("revenueExperiments"));
        for(String d:new String[]{"SECURITY_ROLES","AUDIT_CHAIN","SUSPICIOUS_ACTIVITY","OWNER_BRIEFS","NEXT_BEST_ACTIONS","FORECASTS","EXPERIMENTS"})markDomain(db,d,revision,now);
    }
    static JSONObject status(SQLiteDatabase db){JSONObject o=new JSONObject();try{o.put("auditChainCountNormalized",scalar(db,"SELECT COUNT(*) FROM audit_chain_p3"));o.put("openSuspiciousCountNormalized",scalar(db,"SELECT COUNT(*) FROM suspicious_events_p3 WHERE UPPER(status)='OPEN'"));o.put("ownerBriefCountNormalized",scalar(db,"SELECT COUNT(*) FROM owner_briefs_p3"));o.put("nextBestActionCountNormalized",scalar(db,"SELECT COUNT(*) FROM next_best_actions_p3 WHERE UPPER(status)='SUGGESTED'"));o.put("forecastCountNormalized",scalar(db,"SELECT COUNT(*) FROM forecasts_p3"));o.put("normalizedOwnerDomains",new JSONArray().put("SECURITY_ROLES").put("AUDIT_CHAIN").put("SUSPICIOUS_ACTIVITY").put("OWNER_BRIEFS").put("NEXT_BEST_ACTIONS").put("FORECASTS").put("EXPERIMENTS"));}catch(Exception ignored){}return o;}
    private static void upsertRoles(SQLiteDatabase db,JSONArray rows){if(rows==null)return;for(int i=0;i<rows.length();i++){JSONObject r=rows.optJSONObject(i);if(r==null)continue;String id=r.optString("id","");if(id.isEmpty())continue;ContentValues v=new ContentValues();v.put("id",id);v.put("name",r.optString("name",id));Object p=r.opt("permissions");v.put("permissions_json",p==null?"[]":String.valueOf(p));v.put("system_role",r.optBoolean("system",false)?1:0);v.put("raw_json",r.toString());db.insertWithOnConflict("security_roles_p3",null,v,SQLiteDatabase.CONFLICT_REPLACE);}}
    private static void upsertAudit(SQLiteDatabase db,JSONArray rows){if(rows==null)return;for(int i=0;i<rows.length();i++){JSONObject a=rows.optJSONObject(i);if(a==null)continue;String id=a.optString("id","");if(id.isEmpty())continue;ContentValues v=new ContentValues();v.put("id",id);v.put("at_ms",a.optLong("at",System.currentTimeMillis()));putNullable(v,"actor_id",a.optString("actorId",""));putNullable(v,"actor_role",a.optString("actorRole",""));v.put("action",a.optString("action","UNKNOWN"));putNullable(v,"target",a.optString("target",""));putNullable(v,"detail",a.optString("detail",""));v.put("severity",a.optString("severity","INFO"));v.put("prev_hash",a.optString("prevHash","GENESIS"));v.put("hash",a.optString("hash",""));Object m=a.opt("meta");v.put("meta_json",m==null?"{}":String.valueOf(m));db.insertWithOnConflict("audit_chain_p3",null,v,SQLiteDatabase.CONFLICT_REPLACE);}}
    private static void upsertSuspicious(SQLiteDatabase db,JSONArray rows,long now){if(rows==null)return;for(int i=0;i<rows.length();i++){JSONObject e=rows.optJSONObject(i);if(e==null)continue;String id=e.optString("id","");if(id.isEmpty())continue;ContentValues v=new ContentValues();v.put("id",id);v.put("event_type",e.optString("type","UNKNOWN"));v.put("severity",e.optString("severity","INFO"));v.put("summary",e.optString("summary",id));putNullable(v,"ref_id",e.optString("refId",""));Object ev=e.opt("evidence");v.put("evidence_json",ev==null?"{}":String.valueOf(ev));v.put("status",e.optString("status","OPEN"));v.put("created_at_ms",e.optLong("createdAt",now));putTime(v,"resolved_at_ms",e.opt("resolvedAt"));putNullable(v,"resolution",e.optString("resolution",""));v.put("raw_json",e.toString());db.insertWithOnConflict("suspicious_events_p3",null,v,SQLiteDatabase.CONFLICT_REPLACE);}}
    private static void upsertBriefs(SQLiteDatabase db,JSONArray rows,long now){if(rows==null)return;for(int i=0;i<rows.length();i++){JSONObject b=rows.optJSONObject(i);if(b==null)continue;String id=b.optString("id","");if(id.isEmpty())continue;ContentValues v=new ContentValues();v.put("id",id);v.put("business_day",b.optString("businessDay",""));v.put("generated_at_ms",b.optLong("generatedAt",now));v.put("health_score",b.optInt("healthScore",0));v.put("revenue_minor",money(b.optDouble("revenue",0)));v.put("sessions",b.optInt("sessions",0));v.put("occupancy",b.optInt("occupancy",0));v.put("lost_revenue_minor",money(b.optDouble("lostRevenueEstimate",0)));v.put("forecast_minor",money(b.optDouble("forecast",0)));v.put("forecast_confidence",b.optDouble("forecastConfidence",0));v.put("raw_json",b.toString());db.insertWithOnConflict("owner_briefs_p3",null,v,SQLiteDatabase.CONFLICT_REPLACE);}}
    private static void upsertActions(SQLiteDatabase db,JSONArray rows,long now){if(rows==null)return;for(int i=0;i<rows.length();i++){JSONObject a=rows.optJSONObject(i);if(a==null)continue;String id=a.optString("id","");if(id.isEmpty())continue;ContentValues v=new ContentValues();v.put("id",id);v.put("category",a.optString("category","GENERAL"));v.put("title",a.optString("title",id));putNullable(v,"why",a.optString("why",""));putNullable(v,"estimated_impact",a.optString("estimatedImpact",""));v.put("status",a.optString("status","SUGGESTED"));v.put("generated_at_ms",a.optLong("generatedAt",now));v.put("raw_json",a.toString());db.insertWithOnConflict("next_best_actions_p3",null,v,SQLiteDatabase.CONFLICT_REPLACE);}}
    private static void upsertForecasts(SQLiteDatabase db,JSONArray rows,long now){if(rows==null)return;for(int i=0;i<rows.length();i++){JSONObject f=rows.optJSONObject(i);if(f==null)continue;String id=f.optString("id","");if(id.isEmpty())continue;ContentValues v=new ContentValues();v.put("id",id);v.put("metric",f.optString("metric","UNKNOWN"));v.put("model",f.optString("model","UNKNOWN"));v.put("predicted_minor",money(f.optDouble("predicted",0)));v.put("confidence",f.optDouble("confidence",0));v.put("generated_at_ms",f.optLong("generatedAt",now));v.put("horizon_days",f.optInt("horizonDays",1));if(f.has("actual")&&!f.isNull("actual"))v.put("actual_minor",money(f.optDouble("actual",0)));else v.putNull("actual_minor");if(f.has("error")&&!f.isNull("error"))v.put("error_minor",money(f.optDouble("error",0)));else v.putNull("error_minor");v.put("raw_json",f.toString());db.insertWithOnConflict("forecasts_p3",null,v,SQLiteDatabase.CONFLICT_REPLACE);}}
    private static void upsertExperiments(SQLiteDatabase db,JSONArray rows){if(rows==null)return;for(int i=0;i<rows.length();i++){JSONObject e=rows.optJSONObject(i);if(e==null)continue;String id=e.optString("id","");if(id.isEmpty())continue;ContentValues v=new ContentValues();v.put("id",id);putNullable(v,"name",e.optString("name",""));v.put("status",e.optString("status","DRAFT"));putNullable(v,"hypothesis",e.optString("hypothesis",""));putTime(v,"started_at_ms",e.opt("startedAt"));putTime(v,"ended_at_ms",e.opt("endedAt"));Object b=e.opt("baseline");if(b==null)v.putNull("baseline_json");else v.put("baseline_json",String.valueOf(b));Object r=e.opt("result");if(r==null)v.putNull("result_json");else v.put("result_json",String.valueOf(r));v.put("raw_json",e.toString());db.insertWithOnConflict("revenue_experiments_p3",null,v,SQLiteDatabase.CONFLICT_REPLACE);}}
    private static void markDomain(SQLiteDatabase db,String d,long r,long n){ContentValues v=new ContentValues();v.put("domain",d);v.put("authority","SQLITE_DUAL_WRITE");v.put("migration_state","PARITY_PROVING");v.put("source_revision",r);v.put("updated_at_ms",n);db.insertWithOnConflict("domain_authority",null,v,SQLiteDatabase.CONFLICT_REPLACE);}
    private static long scalar(SQLiteDatabase db,String s){try(Cursor c=db.rawQuery(s,null)){return c.moveToFirst()?c.getLong(0):0;}}
    private static long money(double x){return Math.round(x*100D);}private static void putNullable(ContentValues v,String k,String x){if(x==null||x.trim().isEmpty())v.putNull(k);else v.put(k,x.trim());}private static void putTime(ContentValues v,String k,Object x){long t=time(x);if(t<=0)v.putNull(k);else v.put(k,t);}private static long time(Object x){if(x==null||x==JSONObject.NULL)return 0;if(x instanceof Number)return ((Number)x).longValue();try{return Long.parseLong(String.valueOf(x));}catch(Exception ignored){}try{return java.time.Instant.parse(String.valueOf(x)).toEpochMilli();}catch(Exception ignored){}return 0;}
}
