package com.lapauseclub.manager.core;

import android.content.ContentValues;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;

import org.json.JSONArray;
import org.json.JSONObject;

final class CorePlayerSchemaP4 {
    private CorePlayerSchemaP4() {}
    static void create(SQLiteDatabase db){
        db.execSQL("CREATE TABLE IF NOT EXISTS player_tokens_p4 (id TEXT PRIMARY KEY NOT NULL,customer_id TEXT NOT NULL,session_id TEXT,token_hash TEXT NOT NULL,status TEXT NOT NULL,expires_at_ms INTEGER NOT NULL,created_at_ms INTEGER NOT NULL,used_at_ms INTEGER,raw_json TEXT NOT NULL)");
        db.execSQL("CREATE INDEX IF NOT EXISTS idx_player_tokens_p4_customer ON player_tokens_p4(customer_id,status)");
        db.execSQL("CREATE TABLE IF NOT EXISTS memberships_p4 (id TEXT PRIMARY KEY NOT NULL,customer_id TEXT NOT NULL,membership_type TEXT,status TEXT NOT NULL,starts_at_ms INTEGER,expires_at_ms INTEGER,benefits_json TEXT NOT NULL,raw_json TEXT NOT NULL)");
        db.execSQL("CREATE TABLE IF NOT EXISTS missions_p4 (id TEXT PRIMARY KEY NOT NULL,name TEXT NOT NULL,mission_type TEXT NOT NULL,target_json TEXT NOT NULL,reward_points INTEGER NOT NULL DEFAULT 0,enabled INTEGER NOT NULL DEFAULT 1,raw_json TEXT NOT NULL)");
        db.execSQL("CREATE TABLE IF NOT EXISTS mission_progress_p4 (id TEXT PRIMARY KEY NOT NULL,customer_id TEXT NOT NULL,mission_id TEXT NOT NULL,status TEXT NOT NULL,progress REAL NOT NULL DEFAULT 0,reward_claimed INTEGER NOT NULL DEFAULT 0,updated_at_ms INTEGER NOT NULL,raw_json TEXT NOT NULL)");
        db.execSQL("CREATE INDEX IF NOT EXISTS idx_mission_progress_p4_customer ON mission_progress_p4(customer_id,status)");
        db.execSQL("CREATE TABLE IF NOT EXISTS service_requests_p4 (id TEXT PRIMARY KEY NOT NULL,customer_id TEXT,session_id TEXT,resource_id TEXT,request_type TEXT NOT NULL,status TEXT NOT NULL,priority TEXT NOT NULL,note TEXT,created_at_ms INTEGER NOT NULL,ack_at_ms INTEGER,done_at_ms INTEGER,raw_json TEXT NOT NULL)");
        db.execSQL("CREATE INDEX IF NOT EXISTS idx_service_requests_p4_status ON service_requests_p4(status,priority)");
        db.execSQL("CREATE TABLE IF NOT EXISTS referrals_p4 (id TEXT PRIMARY KEY NOT NULL,referrer_customer_id TEXT NOT NULL,code TEXT NOT NULL,status TEXT NOT NULL,uses INTEGER NOT NULL DEFAULT 0,reward_points INTEGER NOT NULL DEFAULT 0,created_at_ms INTEGER NOT NULL,raw_json TEXT NOT NULL)");
        db.execSQL("CREATE UNIQUE INDEX IF NOT EXISTS idx_referrals_p4_code ON referrals_p4(code)");
        db.execSQL("CREATE TABLE IF NOT EXISTS player_dna_p4 (customer_id TEXT PRIMARY KEY NOT NULL,visits INTEGER NOT NULL DEFAULT 0,last_visit_at_ms INTEGER,favorite_resource_type TEXT,favorite_game TEXT,avg_session_minutes INTEGER NOT NULL DEFAULT 0,total_spend_minor INTEGER NOT NULL DEFAULT 0,visits_per_30_days REAL NOT NULL DEFAULT 0,updated_at_ms INTEGER NOT NULL,raw_json TEXT NOT NULL)");
        db.execSQL("CREATE TABLE IF NOT EXISTS elo_ratings_p4 (id TEXT PRIMARY KEY NOT NULL,customer_id TEXT NOT NULL,game TEXT NOT NULL,rating INTEGER NOT NULL DEFAULT 1000,wins INTEGER NOT NULL DEFAULT 0,losses INTEGER NOT NULL DEFAULT 0,draws INTEGER NOT NULL DEFAULT 0,updated_at_ms INTEGER NOT NULL,raw_json TEXT NOT NULL)");
        db.execSQL("CREATE INDEX IF NOT EXISTS idx_elo_p4_game_rating ON elo_ratings_p4(game,rating DESC)");
        db.execSQL("CREATE TABLE IF NOT EXISTS match_records_p4 (id TEXT PRIMARY KEY NOT NULL,player_a TEXT NOT NULL,player_b TEXT NOT NULL,score_a REAL NOT NULL,score_b REAL NOT NULL,game TEXT NOT NULL,rating_a_after INTEGER,rating_b_after INTEGER,played_at_ms INTEGER NOT NULL,raw_json TEXT NOT NULL)");
        db.execSQL("CREATE TABLE IF NOT EXISTS game_demand_p4 (id TEXT PRIMARY KEY NOT NULL,customer_id TEXT NOT NULL,title TEXT NOT NULL,created_at_ms INTEGER NOT NULL,updated_at_ms INTEGER NOT NULL,raw_json TEXT NOT NULL)");
        db.execSQL("CREATE INDEX IF NOT EXISTS idx_game_demand_p4_title ON game_demand_p4(title)");
        db.execSQL("CREATE TABLE IF NOT EXISTS media_proofs_p4 (id TEXT PRIMARY KEY NOT NULL,command_id TEXT,device_id TEXT,campaign_id TEXT,creative_id TEXT,played_at_ms INTEGER NOT NULL,proof_type TEXT NOT NULL,status TEXT NOT NULL,raw_json TEXT NOT NULL)");
    }
    static void dualWrite(SQLiteDatabase db,JSONObject root,long revision,long now){upsertTokens(db,root.optJSONArray("playerAccessTokens"),now);upsertMemberships(db,root.optJSONArray("memberships"));upsertMissions(db,root.optJSONArray("missions"));upsertMissionProgress(db,root.optJSONArray("missionProgress"),now);upsertServices(db,root.optJSONArray("serviceRequests"),now);upsertReferrals(db,root.optJSONArray("referrals"),now);upsertDna(db,root.optJSONArray("playerDna"),now);upsertElo(db,root.optJSONArray("eloRatings"),now);upsertMatches(db,root.optJSONArray("matchRecords"),now);upsertDemand(db,root.optJSONArray("gameDemandVotes"),now);upsertProofs(db,root.optJSONArray("mediaPlayProofs"),now);for(String d:new String[]{"PLAYER_TOKENS","MEMBERSHIPS","MISSIONS","SERVICE_REQUESTS","REFERRALS","PLAYER_DNA","ELO","MATCH_RECORDS","GAME_DEMAND","MEDIA_PROOFS"})markDomain(db,d,revision,now);}
    static JSONObject status(SQLiteDatabase db){JSONObject o=new JSONObject();try{o.put("activePlayerTokenCountNormalized",scalar(db,"SELECT COUNT(*) FROM player_tokens_p4 WHERE UPPER(status)='ACTIVE'"));o.put("membershipCountNormalized",scalar(db,"SELECT COUNT(*) FROM memberships_p4"));o.put("missionCompletedCountNormalized",scalar(db,"SELECT COUNT(*) FROM mission_progress_p4 WHERE UPPER(status)='COMPLETED'"));o.put("openServiceRequestCountNormalized",scalar(db,"SELECT COUNT(*) FROM service_requests_p4 WHERE UPPER(status) NOT IN ('DONE','CANCELLED')"));o.put("playerDnaCountNormalized",scalar(db,"SELECT COUNT(*) FROM player_dna_p4"));o.put("matchCountNormalized",scalar(db,"SELECT COUNT(*) FROM match_records_p4"));o.put("gameDemandVoteCountNormalized",scalar(db,"SELECT COUNT(*) FROM game_demand_p4"));o.put("proofOfPlayCountNormalized",scalar(db,"SELECT COUNT(*) FROM media_proofs_p4 WHERE UPPER(status)='CONFIRMED'"));o.put("normalizedPlayerDomains",new JSONArray().put("PLAYER_TOKENS").put("MEMBERSHIPS").put("MISSIONS").put("SERVICE_REQUESTS").put("REFERRALS").put("PLAYER_DNA").put("ELO").put("MATCH_RECORDS").put("GAME_DEMAND").put("MEDIA_PROOFS"));}catch(Exception ignored){}return o;}
    private static void upsertTokens(SQLiteDatabase db,JSONArray rows,long now){if(rows==null)return;for(int i=0;i<rows.length();i++){JSONObject t=rows.optJSONObject(i);if(t==null)continue;String id=t.optString("id","");if(id.isEmpty())continue;ContentValues v=new ContentValues();v.put("id",id);v.put("customer_id",t.optString("customerId","unknown"));putNullable(v,"session_id",t.optString("sessionId",""));v.put("token_hash",t.optString("tokenHash",""));v.put("status",t.optString("status","ACTIVE"));v.put("expires_at_ms",t.optLong("expiresAt",now));v.put("created_at_ms",t.optLong("createdAt",now));putTime(v,"used_at_ms",t.opt("usedAt"));v.put("raw_json",t.toString());db.insertWithOnConflict("player_tokens_p4",null,v,SQLiteDatabase.CONFLICT_REPLACE);}}
    private static void upsertMemberships(SQLiteDatabase db,JSONArray rows){if(rows==null)return;for(int i=0;i<rows.length();i++){JSONObject m=rows.optJSONObject(i);if(m==null)continue;String id=m.optString("id","");if(id.isEmpty())continue;ContentValues v=new ContentValues();v.put("id",id);v.put("customer_id",m.optString("customerId","unknown"));putNullable(v,"membership_type",m.optString("type",""));v.put("status",m.optString("status","ACTIVE"));putTime(v,"starts_at_ms",m.opt("startsAt"));putTime(v,"expires_at_ms",m.opt("expiresAt"));Object b=m.opt("benefits");v.put("benefits_json",b==null?"{}":String.valueOf(b));v.put("raw_json",m.toString());db.insertWithOnConflict("memberships_p4",null,v,SQLiteDatabase.CONFLICT_REPLACE);}}
    private static void upsertMissions(SQLiteDatabase db,JSONArray rows){if(rows==null)return;for(int i=0;i<rows.length();i++){JSONObject m=rows.optJSONObject(i);if(m==null)continue;String id=m.optString("id","");if(id.isEmpty())continue;ContentValues v=new ContentValues();v.put("id",id);v.put("name",m.optString("name",id));v.put("mission_type",m.optString("type","UNKNOWN"));Object target=m.opt("target");v.put("target_json",JSONObject.valueToString(target));v.put("reward_points",m.optInt("rewardPoints",0));v.put("enabled",m.optBoolean("enabled",true)?1:0);v.put("raw_json",m.toString());db.insertWithOnConflict("missions_p4",null,v,SQLiteDatabase.CONFLICT_REPLACE);}}
    private static void upsertMissionProgress(SQLiteDatabase db,JSONArray rows,long now){if(rows==null)return;for(int i=0;i<rows.length();i++){JSONObject p=rows.optJSONObject(i);if(p==null)continue;String id=p.optString("id","");if(id.isEmpty())continue;ContentValues v=new ContentValues();v.put("id",id);v.put("customer_id",p.optString("customerId","unknown"));v.put("mission_id",p.optString("missionId","unknown"));v.put("status",p.optString("status","ACTIVE"));v.put("progress",p.optDouble("progress",0));v.put("reward_claimed",p.optBoolean("rewardClaimed",false)?1:0);v.put("updated_at_ms",p.optLong("updatedAt",now));v.put("raw_json",p.toString());db.insertWithOnConflict("mission_progress_p4",null,v,SQLiteDatabase.CONFLICT_REPLACE);}}
    private static void upsertServices(SQLiteDatabase db,JSONArray rows,long now){if(rows==null)return;for(int i=0;i<rows.length();i++){JSONObject r=rows.optJSONObject(i);if(r==null)continue;String id=r.optString("id","");if(id.isEmpty())continue;ContentValues v=new ContentValues();v.put("id",id);putNullable(v,"customer_id",r.optString("customerId",""));putNullable(v,"session_id",r.optString("sessionId",""));putNullable(v,"resource_id",r.optString("resourceId",""));v.put("request_type",r.optString("type","ASSISTANCE"));v.put("status",r.optString("status","NEW"));v.put("priority",r.optString("priority","NORMAL"));putNullable(v,"note",r.optString("note",""));v.put("created_at_ms",r.optLong("createdAt",now));putTime(v,"ack_at_ms",r.opt("ackAt"));putTime(v,"done_at_ms",r.opt("doneAt"));v.put("raw_json",r.toString());db.insertWithOnConflict("service_requests_p4",null,v,SQLiteDatabase.CONFLICT_REPLACE);}}
    private static void upsertReferrals(SQLiteDatabase db,JSONArray rows,long now){if(rows==null)return;for(int i=0;i<rows.length();i++){JSONObject r=rows.optJSONObject(i);if(r==null)continue;String id=r.optString("id","");if(id.isEmpty())continue;ContentValues v=new ContentValues();v.put("id",id);v.put("referrer_customer_id",r.optString("referrerCustomerId","unknown"));v.put("code",r.optString("code",id));v.put("status",r.optString("status","ACTIVE"));v.put("uses",r.optInt("uses",0));v.put("reward_points",r.optInt("rewardPoints",0));v.put("created_at_ms",r.optLong("createdAt",now));v.put("raw_json",r.toString());db.insertWithOnConflict("referrals_p4",null,v,SQLiteDatabase.CONFLICT_REPLACE);}}
    private static void upsertDna(SQLiteDatabase db,JSONArray rows,long now){if(rows==null)return;for(int i=0;i<rows.length();i++){JSONObject d=rows.optJSONObject(i);if(d==null)continue;String id=d.optString("customerId","");if(id.isEmpty())continue;ContentValues v=new ContentValues();v.put("customer_id",id);v.put("visits",d.optInt("visits",0));putTime(v,"last_visit_at_ms",d.opt("lastVisitAt"));putNullable(v,"favorite_resource_type",d.optString("favoriteResourceType",""));putNullable(v,"favorite_game",d.optString("favoriteGame",""));v.put("avg_session_minutes",d.optInt("avgSessionMinutes",0));v.put("total_spend_minor",money(d.optDouble("totalSpend",0)));v.put("visits_per_30_days",d.optDouble("visitsPer30Days",0));v.put("updated_at_ms",d.optLong("updatedAt",now));v.put("raw_json",d.toString());db.insertWithOnConflict("player_dna_p4",null,v,SQLiteDatabase.CONFLICT_REPLACE);}}
    private static void upsertElo(SQLiteDatabase db,JSONArray rows,long now){if(rows==null)return;for(int i=0;i<rows.length();i++){JSONObject e=rows.optJSONObject(i);if(e==null)continue;String id=e.optString("id","");if(id.isEmpty())continue;ContentValues v=new ContentValues();v.put("id",id);v.put("customer_id",e.optString("customerId","unknown"));v.put("game",e.optString("game","GENERAL"));v.put("rating",e.optInt("rating",1000));v.put("wins",e.optInt("wins",0));v.put("losses",e.optInt("losses",0));v.put("draws",e.optInt("draws",0));v.put("updated_at_ms",e.optLong("updatedAt",now));v.put("raw_json",e.toString());db.insertWithOnConflict("elo_ratings_p4",null,v,SQLiteDatabase.CONFLICT_REPLACE);}}
    private static void upsertMatches(SQLiteDatabase db,JSONArray rows,long now){if(rows==null)return;for(int i=0;i<rows.length();i++){JSONObject m=rows.optJSONObject(i);if(m==null)continue;String id=m.optString("id","");if(id.isEmpty())continue;ContentValues v=new ContentValues();v.put("id",id);v.put("player_a",m.optString("playerA","unknown"));v.put("player_b",m.optString("playerB","unknown"));v.put("score_a",m.optDouble("scoreA",0));v.put("score_b",m.optDouble("scoreB",0));v.put("game",m.optString("game","GENERAL"));v.put("rating_a_after",m.optInt("ratingAAfter",1000));v.put("rating_b_after",m.optInt("ratingBAfter",1000));v.put("played_at_ms",m.optLong("playedAt",now));v.put("raw_json",m.toString());db.insertWithOnConflict("match_records_p4",null,v,SQLiteDatabase.CONFLICT_REPLACE);}}
    private static void upsertDemand(SQLiteDatabase db,JSONArray rows,long now){if(rows==null)return;for(int i=0;i<rows.length();i++){JSONObject d=rows.optJSONObject(i);if(d==null)continue;String id=d.optString("id","");if(id.isEmpty())continue;ContentValues v=new ContentValues();v.put("id",id);v.put("customer_id",d.optString("customerId","unknown"));v.put("title",d.optString("title","Unknown"));v.put("created_at_ms",d.optLong("createdAt",now));v.put("updated_at_ms",d.optLong("updatedAt",now));v.put("raw_json",d.toString());db.insertWithOnConflict("game_demand_p4",null,v,SQLiteDatabase.CONFLICT_REPLACE);}}
    private static void upsertProofs(SQLiteDatabase db,JSONArray rows,long now){if(rows==null)return;for(int i=0;i<rows.length();i++){JSONObject p=rows.optJSONObject(i);if(p==null)continue;String id=p.optString("id","");if(id.isEmpty())continue;ContentValues v=new ContentValues();v.put("id",id);putNullable(v,"command_id",p.optString("commandId",""));putNullable(v,"device_id",p.optString("deviceId",""));putNullable(v,"campaign_id",p.optString("campaignId",""));putNullable(v,"creative_id",p.optString("creativeId",""));v.put("played_at_ms",p.optLong("playedAt",now));v.put("proof_type",p.optString("proofType","DEVICE_ACK"));v.put("status",p.optString("status","CONFIRMED"));v.put("raw_json",p.toString());db.insertWithOnConflict("media_proofs_p4",null,v,SQLiteDatabase.CONFLICT_REPLACE);}}
    private static void markDomain(SQLiteDatabase db,String d,long r,long n){ContentValues v=new ContentValues();v.put("domain",d);v.put("authority","SQLITE_DUAL_WRITE");v.put("migration_state","PARITY_PROVING");v.put("source_revision",r);v.put("updated_at_ms",n);db.insertWithOnConflict("domain_authority",null,v,SQLiteDatabase.CONFLICT_REPLACE);}private static long scalar(SQLiteDatabase db,String q){try(Cursor c=db.rawQuery(q,null)){return c.moveToFirst()?c.getLong(0):0;}}private static long money(double x){return Math.round(x*100D);}private static void putNullable(ContentValues v,String k,String x){if(x==null||x.trim().isEmpty())v.putNull(k);else v.put(k,x.trim());}private static void putTime(ContentValues v,String k,Object x){long t=time(x);if(t<=0)v.putNull(k);else v.put(k,t);}private static long time(Object x){if(x==null||x==JSONObject.NULL)return 0;if(x instanceof Number)return ((Number)x).longValue();try{return Long.parseLong(String.valueOf(x));}catch(Exception ignored){}try{return java.time.Instant.parse(String.valueOf(x)).toEpochMilli();}catch(Exception ignored){}return 0;}
}
