package com.lapauseclub.manager.core;

import android.content.ContentValues;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import org.json.JSONArray;
import org.json.JSONObject;

final class CoreSaasSchemaP5 {
 private CoreSaasSchemaP5(){}
 static void create(SQLiteDatabase db){
  db.execSQL("CREATE TABLE IF NOT EXISTS saas_profile_p5 (id TEXT PRIMARY KEY NOT NULL,tenant_id TEXT NOT NULL,venue_id TEXT NOT NULL,branch_id TEXT NOT NULL,protocol_version TEXT NOT NULL,cloud_status TEXT NOT NULL,server_cursor TEXT,last_handshake_at_ms INTEGER,last_sync_at_ms INTEGER,last_error TEXT,raw_json TEXT NOT NULL)");
  db.execSQL("CREATE TABLE IF NOT EXISTS authority_lease_p5 (id TEXT PRIMARY KEY NOT NULL,authority TEXT NOT NULL,lease_id TEXT,expires_at_ms INTEGER,last_server_seen_at_ms INTEGER,emergency_since_ms INTEGER,raw_json TEXT NOT NULL)");
  db.execSQL("CREATE TABLE IF NOT EXISTS entitlements_p5 (id TEXT PRIMARY KEY NOT NULL,plan TEXT NOT NULL,status TEXT NOT NULL,features_json TEXT NOT NULL,issued_at_ms INTEGER,expires_at_ms INTEGER,offline_grace_until_ms INTEGER,last_validated_at_ms INTEGER,raw_json TEXT NOT NULL)");
  db.execSQL("CREATE TABLE IF NOT EXISTS sync_conflicts_p5 (id TEXT PRIMARY KEY NOT NULL,entity_type TEXT,entity_id TEXT,status TEXT NOT NULL,reason TEXT,created_at_ms INTEGER NOT NULL,local_revision INTEGER,remote_revision INTEGER,local_json TEXT,remote_json TEXT,raw_json TEXT NOT NULL)");
  db.execSQL("CREATE INDEX IF NOT EXISTS idx_sync_conflicts_p5_status ON sync_conflicts_p5(status)");
  db.execSQL("CREATE TABLE IF NOT EXISTS automation_rules_p5 (id TEXT PRIMARY KEY NOT NULL,name TEXT NOT NULL,trigger_name TEXT,condition_json TEXT,action_json TEXT,mode TEXT NOT NULL,enabled INTEGER NOT NULL DEFAULT 1,created_at_ms INTEGER,updated_at_ms INTEGER,raw_json TEXT NOT NULL)");
  db.execSQL("CREATE TABLE IF NOT EXISTS automation_runs_p5 (id TEXT PRIMARY KEY NOT NULL,rule_id TEXT,status TEXT NOT NULL,started_at_ms INTEGER,completed_at_ms INTEGER,result_json TEXT,error TEXT,raw_json TEXT NOT NULL)");
  db.execSQL("CREATE TABLE IF NOT EXISTS ai_drafts_p5 (id TEXT PRIMARY KEY NOT NULL,draft_type TEXT,title TEXT NOT NULL,rationale TEXT,tool TEXT NOT NULL,args_json TEXT NOT NULL,status TEXT NOT NULL,created_at_ms INTEGER NOT NULL,approved_at_ms INTEGER,executed_at_ms INTEGER,result_json TEXT,raw_json TEXT NOT NULL)");
  db.execSQL("CREATE INDEX IF NOT EXISTS idx_ai_drafts_p5_status ON ai_drafts_p5(status)");
  db.execSQL("CREATE TABLE IF NOT EXISTS gaming_passports_p5 (id TEXT PRIMARY KEY NOT NULL,customer_id TEXT NOT NULL,pseudonym TEXT NOT NULL,opt_in INTEGER NOT NULL DEFAULT 0,scopes_json TEXT NOT NULL,created_at_ms INTEGER NOT NULL,updated_at_ms INTEGER NOT NULL,raw_json TEXT NOT NULL)");
  db.execSQL("CREATE TABLE IF NOT EXISTS adapter_registry_p5 (id TEXT PRIMARY KEY NOT NULL,name TEXT NOT NULL,adapter_type TEXT NOT NULL,status TEXT NOT NULL,version TEXT,capabilities_json TEXT NOT NULL,raw_json TEXT NOT NULL)");
  CoreAdvancedSchema.create(db);
 }
 static void dualWrite(SQLiteDatabase db,JSONObject root,long revision,long now){upsertProfile(db,root.optJSONObject("saas"),now);upsertLease(db,root.optJSONObject("authorityLease"));upsertEntitlement(db,root.optJSONObject("entitlement"));upsertConflicts(db,root.optJSONArray("syncConflicts"),now);upsertRules(db,root.optJSONArray("automationRules"));upsertRuns(db,root.optJSONArray("automationRuns"));upsertDrafts(db,root.optJSONArray("aiDrafts"),now);upsertPassports(db,root.optJSONArray("gamingPassports"),now);upsertAdapters(db,root.optJSONArray("adapterRegistry"));CoreAdvancedSchema.dualWrite(db,root,revision,now);for(String d:new String[]{"SAAS_PROFILE","AUTHORITY_LEASE","ENTITLEMENT","SYNC_CONFLICTS","AUTOMATIONS","AI_DRAFTS","GAMING_PASSPORT","ADAPTERS"})markDomain(db,d,revision,now);}
 static JSONObject status(SQLiteDatabase db){JSONObject o=new JSONObject();try{o.put("openSyncConflictCountNormalized",scalar(db,"SELECT COUNT(*) FROM sync_conflicts_p5 WHERE UPPER(status)='OPEN'"));o.put("automationRuleCountNormalized",scalar(db,"SELECT COUNT(*) FROM automation_rules_p5 WHERE enabled=1"));o.put("pendingAiDraftCountNormalized",scalar(db,"SELECT COUNT(*) FROM ai_drafts_p5 WHERE UPPER(status) IN ('DRAFT','APPROVED')"));o.put("passportOptInCountNormalized",scalar(db,"SELECT COUNT(*) FROM gaming_passports_p5 WHERE opt_in=1"));o.put("adapterCountNormalized",scalar(db,"SELECT COUNT(*) FROM adapter_registry_p5"));o.put("advanced",CoreAdvancedSchema.status(db));o.put("normalizedSaasDomains",new JSONArray().put("SAAS_PROFILE").put("AUTHORITY_LEASE").put("ENTITLEMENT").put("SYNC_CONFLICTS").put("AUTOMATIONS").put("AI_DRAFTS").put("GAMING_PASSPORT").put("ADAPTERS").put("ADVANCED_CDC"));}catch(Exception ignored){}return o;}
 private static void upsertProfile(SQLiteDatabase db,JSONObject s,long now){if(s==null)return;ContentValues v=new ContentValues();v.put("id","saas-local");v.put("tenant_id",s.optString("tenantId","local"));v.put("venue_id",s.optString("venueId","local"));v.put("branch_id",s.optString("branchId","local"));v.put("protocol_version",s.optString("protocolVersion","la-pause-sync/1"));v.put("cloud_status",s.optString("cloudStatus","UNPAIRED"));putNullable(v,"server_cursor",String.valueOf(s.opt("serverCursor")==JSONObject.NULL?"":s.opt("serverCursor")));putTime(v,"last_handshake_at_ms",s.opt("lastHandshakeAt"));putTime(v,"last_sync_at_ms",s.opt("lastSyncAt"));putNullable(v,"last_error",s.optString("lastError",""));v.put("raw_json",s.toString());db.insertWithOnConflict("saas_profile_p5",null,v,SQLiteDatabase.CONFLICT_REPLACE);}
 private static void upsertLease(SQLiteDatabase db,JSONObject l){if(l==null)return;ContentValues v=new ContentValues();v.put("id","authority-local");v.put("authority",l.optString("authority","TABLET_PRIMARY"));putNullable(v,"lease_id",l.optString("leaseId",""));putTime(v,"expires_at_ms",l.opt("expiresAt"));putTime(v,"last_server_seen_at_ms",l.opt("lastServerSeenAt"));putTime(v,"emergency_since_ms",l.opt("emergencySince"));v.put("raw_json",l.toString());db.insertWithOnConflict("authority_lease_p5",null,v,SQLiteDatabase.CONFLICT_REPLACE);}
 private static void upsertEntitlement(SQLiteDatabase db,JSONObject e){if(e==null)return;ContentValues v=new ContentValues();v.put("id","entitlement-local");v.put("plan",e.optString("plan","LOCAL_CORE"));v.put("status",e.optString("status","ACTIVE"));Object f=e.opt("features");v.put("features_json",f==null?"[]":String.valueOf(f));putTime(v,"issued_at_ms",e.opt("issuedAt"));putTime(v,"expires_at_ms",e.opt("expiresAt"));putTime(v,"offline_grace_until_ms",e.opt("offlineGraceUntil"));putTime(v,"last_validated_at_ms",e.opt("lastValidatedAt"));v.put("raw_json",e.toString());db.insertWithOnConflict("entitlements_p5",null,v,SQLiteDatabase.CONFLICT_REPLACE);}
 private static void upsertConflicts(SQLiteDatabase db,JSONArray a,long now){if(a==null)return;for(int i=0;i<a.length();i++){JSONObject c=a.optJSONObject(i);if(c==null)continue;String id=c.optString("id","");if(id.isEmpty())continue;ContentValues v=new ContentValues();v.put("id",id);putNullable(v,"entity_type",c.optString("entityType",""));putNullable(v,"entity_id",c.optString("entityId",""));v.put("status",c.optString("status","OPEN"));putNullable(v,"reason",c.optString("reason",""));v.put("created_at_ms",c.optLong("createdAt",now));if(c.has("localRevision"))v.put("local_revision",c.optLong("localRevision"));else v.putNull("local_revision");if(c.has("remoteRevision"))v.put("remote_revision",c.optLong("remoteRevision"));else v.putNull("remote_revision");Object l=c.opt("localSnapshot");if(l==null)v.putNull("local_json");else v.put("local_json",String.valueOf(l));Object r=c.opt("remoteSnapshot");if(r==null)v.putNull("remote_json");else v.put("remote_json",String.valueOf(r));v.put("raw_json",c.toString());db.insertWithOnConflict("sync_conflicts_p5",null,v,SQLiteDatabase.CONFLICT_REPLACE);}}
 private static void upsertRules(SQLiteDatabase db,JSONArray a){if(a==null)return;for(int i=0;i<a.length();i++){JSONObject r=a.optJSONObject(i);if(r==null)continue;String id=r.optString("id","");if(id.isEmpty())continue;ContentValues v=new ContentValues();v.put("id",id);v.put("name",r.optString("name",id));putNullable(v,"trigger_name",r.optString("trigger",""));Object c=r.opt("condition");if(c==null)v.putNull("condition_json");else v.put("condition_json",String.valueOf(c));Object act=r.opt("action");if(act==null)v.putNull("action_json");else v.put("action_json",String.valueOf(act));v.put("mode",r.optString("mode","APPROVAL_REQUIRED"));v.put("enabled",r.optBoolean("enabled",true)?1:0);putTime(v,"created_at_ms",r.opt("createdAt"));putTime(v,"updated_at_ms",r.opt("updatedAt"));v.put("raw_json",r.toString());db.insertWithOnConflict("automation_rules_p5",null,v,SQLiteDatabase.CONFLICT_REPLACE);}}
 private static void upsertRuns(SQLiteDatabase db,JSONArray a){if(a==null)return;for(int i=0;i<a.length();i++){JSONObject r=a.optJSONObject(i);if(r==null)continue;String id=r.optString("id","");if(id.isEmpty())continue;ContentValues v=new ContentValues();v.put("id",id);putNullable(v,"rule_id",r.optString("ruleId",""));v.put("status",r.optString("status","UNKNOWN"));putTime(v,"started_at_ms",r.opt("startedAt"));putTime(v,"completed_at_ms",r.opt("completedAt"));Object result=r.opt("result");if(result==null)v.putNull("result_json");else v.put("result_json",String.valueOf(result));putNullable(v,"error",r.optString("error",""));v.put("raw_json",r.toString());db.insertWithOnConflict("automation_runs_p5",null,v,SQLiteDatabase.CONFLICT_REPLACE);}}
 private static void upsertDrafts(SQLiteDatabase db,JSONArray a,long now){if(a==null)return;for(int i=0;i<a.length();i++){JSONObject d=a.optJSONObject(i);if(d==null)continue;String id=d.optString("id","");if(id.isEmpty())continue;ContentValues v=new ContentValues();v.put("id",id);putNullable(v,"draft_type",d.optString("type",""));v.put("title",d.optString("title",id));putNullable(v,"rationale",d.optString("rationale",""));v.put("tool",d.optString("tool","UNKNOWN"));Object args=d.opt("args");v.put("args_json",args==null?"{}":String.valueOf(args));v.put("status",d.optString("status","DRAFT"));v.put("created_at_ms",d.optLong("createdAt",now));putTime(v,"approved_at_ms",d.opt("approvedAt"));putTime(v,"executed_at_ms",d.opt("executedAt"));Object result=d.opt("result");if(result==null)v.putNull("result_json");else v.put("result_json",String.valueOf(result));v.put("raw_json",d.toString());db.insertWithOnConflict("ai_drafts_p5",null,v,SQLiteDatabase.CONFLICT_REPLACE);}}
 private static void upsertPassports(SQLiteDatabase db,JSONArray a,long now){if(a==null)return;for(int i=0;i<a.length();i++){JSONObject p=a.optJSONObject(i);if(p==null)continue;String id=p.optString("id","");if(id.isEmpty())continue;ContentValues v=new ContentValues();v.put("id",id);v.put("customer_id",p.optString("customerId","unknown"));v.put("pseudonym",p.optString("pseudonym",id));v.put("opt_in",p.optBoolean("optIn",false)?1:0);Object s=p.opt("scopes");v.put("scopes_json",s==null?"[]":String.valueOf(s));v.put("created_at_ms",p.optLong("createdAt",now));v.put("updated_at_ms",p.optLong("updatedAt",now));v.put("raw_json",p.toString());db.insertWithOnConflict("gaming_passports_p5",null,v,SQLiteDatabase.CONFLICT_REPLACE);}}
 private static void upsertAdapters(SQLiteDatabase db,JSONArray a){if(a==null)return;for(int i=0;i<a.length();i++){JSONObject p=a.optJSONObject(i);if(p==null)continue;String id=p.optString("id","");if(id.isEmpty())continue;ContentValues v=new ContentValues();v.put("id",id);v.put("name",p.optString("name",id));v.put("adapter_type",p.optString("type","CUSTOM"));v.put("status",p.optString("status","DISABLED"));putNullable(v,"version",p.optString("version",""));Object c=p.opt("capabilities");v.put("capabilities_json",c==null?"[]":String.valueOf(c));v.put("raw_json",p.toString());db.insertWithOnConflict("adapter_registry_p5",null,v,SQLiteDatabase.CONFLICT_REPLACE);}}
 private static void markDomain(SQLiteDatabase db,String d,long r,long n){ContentValues v=new ContentValues();v.put("domain",d);v.put("authority","SQLITE_DUAL_WRITE");v.put("migration_state","PARITY_PROVING");v.put("source_revision",r);v.put("updated_at_ms",n);db.insertWithOnConflict("domain_authority",null,v,SQLiteDatabase.CONFLICT_REPLACE);}private static long scalar(SQLiteDatabase db,String q){try(Cursor c=db.rawQuery(q,null)){return c.moveToFirst()?c.getLong(0):0;}}private static void putNullable(ContentValues v,String k,String x){if(x==null||x.trim().isEmpty())v.putNull(k);else v.put(k,x.trim());}private static void putTime(ContentValues v,String k,Object x){long t=time(x);if(t<=0)v.putNull(k);else v.put(k,t);}private static long time(Object x){if(x==null||x==JSONObject.NULL)return 0;if(x instanceof Number)return ((Number)x).longValue();try{return Long.parseLong(String.valueOf(x));}catch(Exception ignored){}try{return java.time.Instant.parse(String.valueOf(x)).toEpochMilli();}catch(Exception ignored){}return 0;}
}
