package com.lapauseclub.manager.core;

import android.content.ContentValues;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import org.json.JSONArray;
import org.json.JSONObject;

/** Final CDC consolidation tables. Money-critical fields use integer minor units. */
final class CoreAdvancedSchema {
 private CoreAdvancedSchema(){}
 static void create(SQLiteDatabase db){
  db.execSQL("CREATE TABLE IF NOT EXISTS credit_notes_adv (id TEXT PRIMARY KEY NOT NULL,customer_id TEXT,amount_minor INTEGER NOT NULL,balance_minor INTEGER NOT NULL,status TEXT NOT NULL,source_payment_id TEXT,issued_at_ms INTEGER NOT NULL,expires_at_ms INTEGER,raw_json TEXT NOT NULL)");
  db.execSQL("CREATE TABLE IF NOT EXISTS vouchers_adv (id TEXT PRIMARY KEY NOT NULL,code TEXT NOT NULL,customer_id TEXT,initial_minor INTEGER NOT NULL,balance_minor INTEGER NOT NULL,status TEXT NOT NULL,issued_at_ms INTEGER NOT NULL,expires_at_ms INTEGER,raw_json TEXT NOT NULL)");
  db.execSQL("CREATE UNIQUE INDEX IF NOT EXISTS idx_vouchers_adv_code ON vouchers_adv(code)");
  db.execSQL("CREATE TABLE IF NOT EXISTS stock_counts_adv (id TEXT PRIMARY KEY NOT NULL,status TEXT NOT NULL,started_at_ms INTEGER NOT NULL,completed_at_ms INTEGER,lines_json TEXT NOT NULL,raw_json TEXT NOT NULL)");
  db.execSQL("CREATE TABLE IF NOT EXISTS goods_receipts_adv (id TEXT PRIMARY KEY NOT NULL,product_id TEXT NOT NULL,qty REAL NOT NULL,unit_cost_minor INTEGER NOT NULL,supplier TEXT,po_id TEXT,received_at_ms INTEGER NOT NULL,raw_json TEXT NOT NULL)");
  db.execSQL("CREATE TABLE IF NOT EXISTS fleet_samples_adv (id TEXT PRIMARY KEY NOT NULL,at_ms INTEGER NOT NULL,online INTEGER NOT NULL,offline INTEGER NOT NULL,degraded INTEGER NOT NULL,active_leases INTEGER NOT NULL,pending_commands INTEGER NOT NULL,blocked_resources INTEGER NOT NULL,raw_json TEXT NOT NULL)");
  db.execSQL("CREATE TABLE IF NOT EXISTS auto_heal_adv (id TEXT PRIMARY KEY NOT NULL,device_id TEXT NOT NULL,command_id TEXT,action TEXT NOT NULL,status TEXT NOT NULL,at_ms INTEGER NOT NULL,raw_json TEXT NOT NULL)");
  db.execSQL("CREATE TABLE IF NOT EXISTS experience_scores_adv (id TEXT PRIMARY KEY NOT NULL,customer_id TEXT NOT NULL,score REAL NOT NULL,at_ms INTEGER NOT NULL,dimensions_json TEXT NOT NULL,note TEXT,raw_json TEXT NOT NULL)");
  db.execSQL("CREATE TABLE IF NOT EXISTS campaigns_adv (id TEXT PRIMARY KEY NOT NULL,name TEXT NOT NULL,status TEXT NOT NULL,sponsor TEXT,device_ids_json TEXT NOT NULL,brand_safety_json TEXT NOT NULL,created_at_ms INTEGER NOT NULL,updated_at_ms INTEGER NOT NULL,raw_json TEXT NOT NULL)");
  db.execSQL("CREATE TABLE IF NOT EXISTS releases_adv (id TEXT PRIMARY KEY NOT NULL,title TEXT NOT NULL,status TEXT NOT NULL,release_date_ms INTEGER,demand_votes INTEGER NOT NULL DEFAULT 0,license_status TEXT,purchase_decision TEXT,updated_at_ms INTEGER NOT NULL,raw_json TEXT NOT NULL)");
  db.execSQL("CREATE TABLE IF NOT EXISTS revenue_reports_adv (id TEXT PRIMARY KEY NOT NULL,period_start_ms INTEGER,period_end_ms INTEGER,actual_revenue_minor INTEGER NOT NULL,attributed_minor INTEGER NOT NULL,estimated_opportunity_minor INTEGER NOT NULL,sessions INTEGER NOT NULL,players INTEGER NOT NULL,generated_at_ms INTEGER NOT NULL,raw_json TEXT NOT NULL)");
  db.execSQL("CREATE TABLE IF NOT EXISTS feature_flags_adv (flag_key TEXT PRIMARY KEY NOT NULL,enabled INTEGER NOT NULL,source TEXT NOT NULL,updated_at_ms INTEGER NOT NULL,raw_json TEXT NOT NULL)");
  db.execSQL("CREATE TABLE IF NOT EXISTS scheduled_jobs_adv (id TEXT PRIMARY KEY NOT NULL,name TEXT NOT NULL,kind TEXT NOT NULL,enabled INTEGER NOT NULL,status TEXT NOT NULL,last_run_at_ms INTEGER,raw_json TEXT NOT NULL)");
  db.execSQL("CREATE TABLE IF NOT EXISTS onboarding_adv (id TEXT PRIMARY KEY NOT NULL,status TEXT NOT NULL,started_at_ms INTEGER NOT NULL,completed_at_ms INTEGER,steps_json TEXT NOT NULL,raw_json TEXT NOT NULL)");
  db.execSQL("CREATE TABLE IF NOT EXISTS white_label_adv (id TEXT PRIMARY KEY NOT NULL,name TEXT,accent TEXT,logo_ref TEXT,status TEXT NOT NULL,updated_at_ms INTEGER NOT NULL,raw_json TEXT NOT NULL)");
  db.execSQL("CREATE TABLE IF NOT EXISTS extended_records_adv (domain TEXT NOT NULL,entity_id TEXT NOT NULL,updated_at_ms INTEGER NOT NULL,raw_json TEXT NOT NULL,PRIMARY KEY(domain,entity_id))");
  db.execSQL("CREATE INDEX IF NOT EXISTS idx_extended_records_adv_domain ON extended_records_adv(domain,updated_at_ms DESC)");
 }
 static void dualWrite(SQLiteDatabase db,JSONObject root,long revision,long now){create(db);credits(db,root.optJSONArray("creditNotes"),now);vouchers(db,root.optJSONArray("vouchers"),now);counts(db,root.optJSONArray("stockCounts"),now);receipts(db,root.optJSONArray("goodsReceipts"),now);fleet(db,root.optJSONArray("observabilitySamples"),now);heals(db,root.optJSONArray("autoHealRuns"),now);cx(db,root.optJSONArray("experienceScores"),now);campaigns(db,root.optJSONArray("campaignsP4"),now);releases(db,root.optJSONArray("releaseCenter"),now);reports(db,root.optJSONArray("monthlyValueReports"),now);flags(db,root.optJSONArray("featureFlags"),now);jobs(db,root.optJSONArray("scheduledJobs"),now);onboarding(db,root.optJSONArray("onboardingRuns"),now);white(db,root.optJSONArray("whiteLabelProfiles"),now);generic(db,"GROUP_TABS",root.optJSONArray("groupTabs"),now);generic(db,"RECEIPTS",root.optJSONArray("receipts"),now);generic(db,"VENUE_CREDIT",root.optJSONArray("venueCreditLedger"),now);generic(db,"PARTY_GROUPS",root.optJSONArray("partyGroups"),now);generic(db,"SPONSOR_REPORTS",root.optJSONArray("sponsorReports"),now);generic(db,"LICENSE_VAULT_META",root.optJSONArray("licenseVaultMeta"),now);generic(db,"DYNAMIC_LOYALTY",root.optJSONArray("dynamicLoyaltySuggestions"),now);generic(db,"SMART_SEAT",root.optJSONArray("smartSeatSuggestions"),now);generic(db,"INVENTORY_BRAIN",root.optJSONArray("inventorySuggestions"),now);generic(db,"HARDWARE_ROI",root.optJSONArray("hardwareRoi"),now);generic(db,"AUTOMATION_ROI",root.optJSONArray("automationMetrics"),now);generic(db,"STAFF_PLAN",root.optJSONArray("staffPlans"),now);generic(db,"ENERGY_SUGGESTIONS",root.optJSONArray("energySuggestions"),now);generic(db,"DATA_REQUESTS",root.optJSONArray("dataRequests"),now);generic(db,"EVENT_SCHEMAS",root.optJSONArray("eventSchemas"),now);generic(db,"RETENTION_POLICIES",root.optJSONArray("dataRetentionPolicies"),now);for(String d:new String[]{"CREDIT_NOTES","VOUCHERS","STOCK_COUNTS","GOODS_RECEIPTS","FLEET_OBSERVABILITY","AUTO_HEAL","EXPERIENCE_SCORE","CAMPAIGNS","RELEASE_CENTER","REVENUE_INTELLIGENCE","FEATURE_FLAGS","SCHEDULER","ONBOARDING","WHITE_LABEL"})mark(db,d,revision,now);}
 static JSONObject status(SQLiteDatabase db){JSONObject o=new JSONObject();try{o.put("creditNoteCount",scalar(db,"SELECT COUNT(*) FROM credit_notes_adv WHERE status='ACTIVE'"));o.put("voucherCount",scalar(db,"SELECT COUNT(*) FROM vouchers_adv WHERE status='ACTIVE'"));o.put("stockCountCount",scalar(db,"SELECT COUNT(*) FROM stock_counts_adv"));o.put("campaignCount",scalar(db,"SELECT COUNT(*) FROM campaigns_adv"));o.put("experienceScoreCount",scalar(db,"SELECT COUNT(*) FROM experience_scores_adv"));o.put("revenueReportCount",scalar(db,"SELECT COUNT(*) FROM revenue_reports_adv"));o.put("featureFlagCount",scalar(db,"SELECT COUNT(*) FROM feature_flags_adv"));o.put("scheduledJobCount",scalar(db,"SELECT COUNT(*) FROM scheduled_jobs_adv WHERE enabled=1"));o.put("extendedRecordCount",scalar(db,"SELECT COUNT(*) FROM extended_records_adv"));}catch(Exception ignored){}return o;}
 private static void credits(SQLiteDatabase db,JSONArray a,long n){if(a==null)return;for(int i=0;i<a.length();i++){JSONObject x=a.optJSONObject(i);if(x==null||x.optString("id","").isEmpty())continue;ContentValues v=new ContentValues();v.put("id",x.optString("id"));nullable(v,"customer_id",x.optString("customerId",""));v.put("amount_minor",money(x.optDouble("amount",0)));v.put("balance_minor",money(x.optDouble("balance",0)));v.put("status",x.optString("status","ACTIVE"));nullable(v,"source_payment_id",x.optString("sourcePaymentId",""));v.put("issued_at_ms",x.optLong("issuedAt",n));time(v,"expires_at_ms",x.opt("expiresAt"));v.put("raw_json",x.toString());db.insertWithOnConflict("credit_notes_adv",null,v,SQLiteDatabase.CONFLICT_REPLACE);}}
 private static void vouchers(SQLiteDatabase db,JSONArray a,long n){if(a==null)return;for(int i=0;i<a.length();i++){JSONObject x=a.optJSONObject(i);if(x==null||x.optString("id","").isEmpty())continue;ContentValues v=new ContentValues();v.put("id",x.optString("id"));v.put("code",x.optString("code",x.optString("id")));nullable(v,"customer_id",x.optString("customerId",""));v.put("initial_minor",money(x.optDouble("initialAmount",0)));v.put("balance_minor",money(x.optDouble("balance",0)));v.put("status",x.optString("status","ACTIVE"));v.put("issued_at_ms",x.optLong("issuedAt",n));time(v,"expires_at_ms",x.opt("expiresAt"));v.put("raw_json",x.toString());db.insertWithOnConflict("vouchers_adv",null,v,SQLiteDatabase.CONFLICT_REPLACE);}}
 private static void counts(SQLiteDatabase db,JSONArray a,long n){if(a==null)return;for(int i=0;i<a.length();i++){JSONObject x=a.optJSONObject(i);if(x==null||x.optString("id","").isEmpty())continue;ContentValues v=new ContentValues();v.put("id",x.optString("id"));v.put("status",x.optString("status","OPEN"));v.put("started_at_ms",x.optLong("startedAt",n));time(v,"completed_at_ms",x.opt("completedAt"));v.put("lines_json",String.valueOf(x.opt("lines")));v.put("raw_json",x.toString());db.insertWithOnConflict("stock_counts_adv",null,v,SQLiteDatabase.CONFLICT_REPLACE);}}
 private static void receipts(SQLiteDatabase db,JSONArray a,long n){if(a==null)return;for(int i=0;i<a.length();i++){JSONObject x=a.optJSONObject(i);if(x==null||x.optString("id","").isEmpty())continue;ContentValues v=new ContentValues();v.put("id",x.optString("id"));v.put("product_id",x.optString("productId","unknown"));v.put("qty",x.optDouble("qty",0));v.put("unit_cost_minor",money(x.optDouble("unitCost",0)));nullable(v,"supplier",x.optString("supplier",""));nullable(v,"po_id",x.optString("poId",""));v.put("received_at_ms",x.optLong("receivedAt",n));v.put("raw_json",x.toString());db.insertWithOnConflict("goods_receipts_adv",null,v,SQLiteDatabase.CONFLICT_REPLACE);}}
 private static void fleet(SQLiteDatabase db,JSONArray a,long n){if(a==null)return;for(int i=0;i<a.length();i++){JSONObject x=a.optJSONObject(i);if(x==null||x.optString("id","").isEmpty())continue;ContentValues v=new ContentValues();v.put("id",x.optString("id"));v.put("at_ms",x.optLong("at",n));v.put("online",x.optInt("online",0));v.put("offline",x.optInt("offline",0));v.put("degraded",x.optInt("degraded",0));v.put("active_leases",x.optInt("activeLeases",0));v.put("pending_commands",x.optInt("pendingCommands",0));v.put("blocked_resources",x.optInt("blockedResources",0));v.put("raw_json",x.toString());db.insertWithOnConflict("fleet_samples_adv",null,v,SQLiteDatabase.CONFLICT_REPLACE);}}
 private static void heals(SQLiteDatabase db,JSONArray a,long n){if(a==null)return;for(int i=0;i<a.length();i++){JSONObject x=a.optJSONObject(i);if(x==null||x.optString("id","").isEmpty())continue;ContentValues v=new ContentValues();v.put("id",x.optString("id"));v.put("device_id",x.optString("deviceId","unknown"));nullable(v,"command_id",x.optString("commandId",""));v.put("action",x.optString("action","UNKNOWN"));v.put("status",x.optString("status","QUEUED"));v.put("at_ms",x.optLong("at",n));v.put("raw_json",x.toString());db.insertWithOnConflict("auto_heal_adv",null,v,SQLiteDatabase.CONFLICT_REPLACE);}}
 private static void cx(SQLiteDatabase db,JSONArray a,long n){if(a==null)return;for(int i=0;i<a.length();i++){JSONObject x=a.optJSONObject(i);if(x==null||x.optString("id","").isEmpty())continue;ContentValues v=new ContentValues();v.put("id",x.optString("id"));v.put("customer_id",x.optString("customerId","unknown"));v.put("score",x.optDouble("score",0));v.put("at_ms",x.optLong("at",n));v.put("dimensions_json",String.valueOf(x.opt("dimensions")));nullable(v,"note",x.optString("note",""));v.put("raw_json",x.toString());db.insertWithOnConflict("experience_scores_adv",null,v,SQLiteDatabase.CONFLICT_REPLACE);}}
 private static void campaigns(SQLiteDatabase db,JSONArray a,long n){if(a==null)return;for(int i=0;i<a.length();i++){JSONObject x=a.optJSONObject(i);if(x==null||x.optString("id","").isEmpty())continue;ContentValues v=new ContentValues();v.put("id",x.optString("id"));v.put("name",x.optString("name",x.optString("id")));v.put("status",x.optString("status","DRAFT"));nullable(v,"sponsor",x.optString("sponsor",""));v.put("device_ids_json",String.valueOf(x.opt("deviceIds")));v.put("brand_safety_json",String.valueOf(x.opt("brandSafety")));v.put("created_at_ms",x.optLong("createdAt",n));v.put("updated_at_ms",x.optLong("updatedAt",n));v.put("raw_json",x.toString());db.insertWithOnConflict("campaigns_adv",null,v,SQLiteDatabase.CONFLICT_REPLACE);}}
 private static void releases(SQLiteDatabase db,JSONArray a,long n){if(a==null)return;for(int i=0;i<a.length();i++){JSONObject x=a.optJSONObject(i);if(x==null||x.optString("id","").isEmpty())continue;ContentValues v=new ContentValues();v.put("id",x.optString("id"));v.put("title",x.optString("title",x.optString("id")));v.put("status",x.optString("status","WATCHING"));time(v,"release_date_ms",x.opt("releaseDate"));v.put("demand_votes",x.optInt("demandVotes",0));nullable(v,"license_status",x.optString("licenseStatus",""));nullable(v,"purchase_decision",x.optString("purchaseDecision",""));v.put("updated_at_ms",x.optLong("updatedAt",n));v.put("raw_json",x.toString());db.insertWithOnConflict("releases_adv",null,v,SQLiteDatabase.CONFLICT_REPLACE);}}
 private static void reports(SQLiteDatabase db,JSONArray a,long n){if(a==null)return;for(int i=0;i<a.length();i++){JSONObject x=a.optJSONObject(i);if(x==null||x.optString("id","").isEmpty())continue;ContentValues v=new ContentValues();v.put("id",x.optString("id"));v.put("period_start_ms",x.optLong("periodStart",0));v.put("period_end_ms",x.optLong("periodEnd",0));v.put("actual_revenue_minor",money(x.optDouble("actualRevenue",0)));v.put("attributed_minor",money(x.optDouble("attributedAutomation",0)));v.put("estimated_opportunity_minor",money(x.optDouble("estimatedOpportunity",0)));v.put("sessions",x.optInt("sessions",0));v.put("players",x.optInt("players",0));v.put("generated_at_ms",x.optLong("generatedAt",n));v.put("raw_json",x.toString());db.insertWithOnConflict("revenue_reports_adv",null,v,SQLiteDatabase.CONFLICT_REPLACE);}}
 private static void flags(SQLiteDatabase db,JSONArray a,long n){if(a==null)return;for(int i=0;i<a.length();i++){JSONObject x=a.optJSONObject(i);if(x==null||x.optString("key","").isEmpty())continue;ContentValues v=new ContentValues();v.put("flag_key",x.optString("key"));v.put("enabled",x.optBoolean("enabled",false)?1:0);v.put("source",x.optString("source","LOCAL"));v.put("updated_at_ms",x.optLong("updatedAt",n));v.put("raw_json",x.toString());db.insertWithOnConflict("feature_flags_adv",null,v,SQLiteDatabase.CONFLICT_REPLACE);}}
 private static void jobs(SQLiteDatabase db,JSONArray a,long n){if(a==null)return;for(int i=0;i<a.length();i++){JSONObject x=a.optJSONObject(i);if(x==null||x.optString("id","").isEmpty())continue;ContentValues v=new ContentValues();v.put("id",x.optString("id"));v.put("name",x.optString("name",x.optString("id")));v.put("kind",x.optString("kind","UNKNOWN"));v.put("enabled",x.optBoolean("enabled",true)?1:0);v.put("status",x.optString("status","IDLE"));time(v,"last_run_at_ms",x.opt("lastRunAt"));v.put("raw_json",x.toString());db.insertWithOnConflict("scheduled_jobs_adv",null,v,SQLiteDatabase.CONFLICT_REPLACE);}}
 private static void onboarding(SQLiteDatabase db,JSONArray a,long n){if(a==null)return;for(int i=0;i<a.length();i++){JSONObject x=a.optJSONObject(i);if(x==null||x.optString("id","").isEmpty())continue;ContentValues v=new ContentValues();v.put("id",x.optString("id"));v.put("status",x.optString("status","IN_PROGRESS"));v.put("started_at_ms",x.optLong("startedAt",n));time(v,"completed_at_ms",x.opt("completedAt"));v.put("steps_json",String.valueOf(x.opt("steps")));v.put("raw_json",x.toString());db.insertWithOnConflict("onboarding_adv",null,v,SQLiteDatabase.CONFLICT_REPLACE);}}
 private static void white(SQLiteDatabase db,JSONArray a,long n){if(a==null)return;for(int i=0;i<a.length();i++){JSONObject x=a.optJSONObject(i);if(x==null||x.optString("id","").isEmpty())continue;ContentValues v=new ContentValues();v.put("id",x.optString("id"));nullable(v,"name",x.optString("name",""));nullable(v,"accent",x.optString("accent",""));nullable(v,"logo_ref",x.optString("logoRef",""));v.put("status",x.optString("status","LOCAL_PREVIEW"));v.put("updated_at_ms",x.optLong("updatedAt",n));v.put("raw_json",x.toString());db.insertWithOnConflict("white_label_adv",null,v,SQLiteDatabase.CONFLICT_REPLACE);}}
 private static void generic(SQLiteDatabase db,String domain,JSONArray a,long n){if(a==null)return;for(int i=0;i<a.length();i++){JSONObject x=a.optJSONObject(i);if(x==null)continue;String id=x.optString("id",domain+"-"+i);ContentValues v=new ContentValues();v.put("domain",domain);v.put("entity_id",id);v.put("updated_at_ms",x.optLong("updatedAt",x.optLong("at",n)));v.put("raw_json",x.toString());db.insertWithOnConflict("extended_records_adv",null,v,SQLiteDatabase.CONFLICT_REPLACE);}}
 private static void mark(SQLiteDatabase db,String d,long r,long n){ContentValues v=new ContentValues();v.put("domain",d);v.put("authority","SQLITE_DUAL_WRITE");v.put("migration_state","PARITY_PROVING");v.put("source_revision",r);v.put("updated_at_ms",n);db.insertWithOnConflict("domain_authority",null,v,SQLiteDatabase.CONFLICT_REPLACE);}private static long scalar(SQLiteDatabase db,String q){try(Cursor c=db.rawQuery(q,null)){return c.moveToFirst()?c.getLong(0):0;}}private static long money(double x){return Math.round(x*100D);}private static void nullable(ContentValues v,String k,String x){if(x==null||x.trim().isEmpty())v.putNull(k);else v.put(k,x.trim());}private static void time(ContentValues v,String k,Object x){long t=toTime(x);if(t<=0)v.putNull(k);else v.put(k,t);}private static long toTime(Object x){if(x==null||x==JSONObject.NULL)return 0;if(x instanceof Number)return ((Number)x).longValue();try{return Long.parseLong(String.valueOf(x));}catch(Exception ignored){}try{return java.time.Instant.parse(String.valueOf(x)).toEpochMilli();}catch(Exception ignored){}return 0;}
}
