'use strict';
/* LA PAUSE OS v2.3 — operator-first control center + contextual session UX.
   This is an authoritative UI/business compatibility layer, not a parallel shell. */
(function(){
  const LP=window.LPClient;if(!LP)return;
  const TYPES=LP.types||[];
  const TYPE_MEDIA={
    CONSOLE:'media/premium/ps5.jpg',SIM_RACING:'media/premium/sim.jpg',PC_GAMING:'media/premium/pc.jpg',
    BILLIARD_TABLE:'media/premium/billiard.jpg',SNOOKER_TABLE:'media/premium/snooker.jpg',TABLE_TENNIS:'media/premium/table-tennis.jpg',
    PRIVATE_ROOM:'media/premium/lounge.jpg',CUSTOM:'media/premium/arcade.jpg'
  };
  const LEGACY_TYPE={CONSOLE:'PS5',SIM_RACING:'SIM',PC_GAMING:'PC',BILLIARD_TABLE:'BILLIARD',SNOOKER_TABLE:'SNOOKER',TABLE_TENNIS:'TABLE_TENNIS',PRIVATE_ROOM:'PRIVATE_ROOM',CUSTOM:'CUSTOM'};
  const MODEL={TIME:'TIME_PRORATED',BLOCK:'TIME_BLOCK',FIXED:'FIXED_SESSION',GAME:'PER_GAME',PLAYER_GAME:'PER_PLAYER_GAME',CUSTOM:'CUSTOM_AMOUNT'};
  const PROFILE={
    CONSOLE:{label:'Console / PS5',defaultModel:MODEL.TIME,models:[MODEL.TIME],players:true,game:true,presets:[30,60,120],open:true,budget:true},
    SIM_RACING:{label:'Sim Racing',defaultModel:MODEL.TIME,models:[MODEL.TIME,MODEL.BLOCK,MODEL.FIXED],players:false,game:true,presets:[15,30,60],open:false,budget:false},
    PC_GAMING:{label:'PC Gaming',defaultModel:MODEL.TIME,models:[MODEL.TIME,MODEL.BLOCK],players:false,game:true,presets:[30,60,120],open:true,budget:true},
    BILLIARD_TABLE:{label:'Billard',defaultModel:MODEL.GAME,models:[MODEL.GAME,MODEL.PLAYER_GAME,MODEL.TIME,MODEL.BLOCK],players:true,game:false,presets:[1,2,3],open:true,budget:false},
    SNOOKER_TABLE:{label:'Snooker',defaultModel:MODEL.GAME,models:[MODEL.GAME,MODEL.PLAYER_GAME,MODEL.TIME,MODEL.BLOCK],players:true,game:false,presets:[1,2,3],open:true,budget:false},
    TABLE_TENNIS:{label:'Tennis de table',defaultModel:MODEL.TIME,models:[MODEL.TIME,MODEL.BLOCK,MODEL.FIXED],players:true,game:false,presets:[30,60,90],open:true,budget:false},
    PRIVATE_ROOM:{label:'Salle privée',defaultModel:MODEL.BLOCK,models:[MODEL.BLOCK,MODEL.TIME,MODEL.FIXED],players:true,game:false,presets:[60,120,180],open:false,budget:false},
    CUSTOM:{label:'Activité',defaultModel:MODEL.FIXED,models:[MODEL.FIXED,MODEL.TIME,MODEL.BLOCK,MODEL.GAME,MODEL.CUSTOM],players:true,game:false,presets:[1],open:false,budget:false}
  };
  const MODEL_LABEL={
    TIME:'Au temps',TIME_PRORATED:'Au temps',TIME_BLOCK:'Bloc de temps',FIXED_SESSION:'Prix fixe',PER_GAME:'Par partie',PER_PLAYER_GAME:'Par partie / joueurs',CUSTOM_AMOUNT:'Montant libre'
  };
  LP.opsModel=MODEL;LP.opsProfiles=PROFILE;

  function save(eventType,entityId,payload){try{saveState({eventType,entityId:entityId||null,payload:payload||null})}catch(_){try{saveState()}catch(__){}}}
  function typeOf(st){return LP.typeOf(st)}
  function profile(st){return PROFILE[typeOf(st)]||PROFILE.CUSTOM}
  function typePlanFor(t){return (state.ratePlans||[]).find(x=>x.enabled!==false&&x.scope==='TYPE'&&String(x.resourceType||'').toUpperCase()===String(t||'').toUpperCase())||null}
  function planFor(st){try{return p1PlanFor(st)}catch(_){return st?typePlanFor(typeOf(st)):null}}
  function existingModel(plan,resourceType=''){
    const t=String(resourceType||plan?.resourceType||'').toUpperCase();
    // Old generic hourly plans for billiard/snooker were generated by the previous wizard.
    // Do not silently preserve a commercially wrong model: force explicit per-game setup instead.
    if(!plan?.billingModel&&['BILLIARD_TABLE','SNOOKER_TABLE'].includes(t)&&['FLAT_HOURLY','PER_HOUR_PLAYERS','PER_PLAYER_HOURLY'].includes(String(plan?.pricingModel||'')))return null;
    if(plan?.billingModel)return plan.billingModel;
    const p=String(plan?.pricingModel||'');
    if(['FLAT_HOURLY','PER_HOUR_PLAYERS','PER_PLAYER_HOURLY'].includes(p))return MODEL.TIME;
    if(['TIME_BLOCK','FIXED_SESSION','PER_GAME','PER_PLAYER_GAME','CUSTOM_AMOUNT'].includes(p))return p;
    return null;
  }
  function modelFor(st){return existingModel(planFor(st),typeOf(st))||profile(st).defaultModel}
  function clientName(c){return c?(c.name||[c.firstName,c.lastName].filter(Boolean).join(' ')||c.alias||'Client'):'Client passage'}
  LP.clientName=clientName;
  function byData(attr,value){return Array.from(document.querySelectorAll(`[${attr}]`)).find(el=>el.getAttribute(attr)===String(value))||null}

  function ensureOpsState(){
    state.resourceMedia=state.resourceMedia||{};state.resourceMediaPosition=state.resourceMediaPosition||{};
    TYPES.forEach(t=>{if(!state.resourceMedia[t])state.resourceMedia[t]=TYPE_MEDIA[t]||LP.media[t]||TYPE_MEDIA.CUSTOM;if(!state.resourceMediaPosition[t])state.resourceMediaPosition[t]='center'});
    state.ratePlans=Array.isArray(state.ratePlans)?state.ratePlans:[];
    state.stations=Array.isArray(state.stations)?state.stations:[];
    state.stations.forEach(st=>{st.osResourceType=typeOf(st);if(!st.mediaPosition)st.mediaPosition='center'});
  }
  ensureOpsState();

  LP.imageFor=(st,s)=>{
    if(s?.coverUrl)return s.coverUrl; // compatibility only: new UX never asks for it
    const t=typeOf(st);return st?.mediaUrl||st?.defaultMedia||state.resourceMedia?.[t]||TYPE_MEDIA[t]||LP.media[t]||TYPE_MEDIA.CUSTOM;
  };
  LP.mediaPositionFor=st=>st?.mediaPosition||state.resourceMediaPosition?.[typeOf(st)]||'center';

  function playerRate(plan,players){
    const rates=plan?.playerRates||{};return LP.n(rates[String(players)],LP.n(rates[players],0));
  }
  function hourlyRate(st,players=1){
    const p=planFor(st),m=modelFor(st);
    if(m!==MODEL.TIME)return 0;
    if(['PER_HOUR_PLAYERS','PER_PLAYER_HOURLY'].includes(String(p?.pricingModel||''))){const r=playerRate(p,players);if(r>0)return r;}
    const configured=LP.n(p?.hourlyRate,0);if(configured>0)return configured;
    try{return p1RateFor(st,players)}catch(_){return 0}
  }
  function unitPrice(st,players=1){
    const p=planFor(st),m=modelFor(st);
    if(m===MODEL.GAME)return LP.n(p?.unitPrice,LP.n(p?.gamePrice,0));
    if(m===MODEL.PLAYER_GAME)return playerRate(p,players)||LP.n(p?.unitPrice,0);
    if(m===MODEL.FIXED)return LP.n(p?.fixedPrice,LP.n(p?.sessionPrice,LP.n(p?.unitPrice,0)));
    if(m===MODEL.BLOCK)return LP.n(p?.blockPrice,LP.n(p?.unitPrice,0));
    return 0;
  }
  function blockMinutes(st){return Math.max(1,LP.n(planFor(st)?.blockMinutes,30))}
  function round(v){return Math.max(0,roundTo(LP.n(v),LP.n(state.rates?.rounding,.5)))}
  function rateLabel(st,players=1){
    const p=planFor(st),m=modelFor(st);
    if(m===MODEL.TIME){const r=hourlyRate(st,players);return r>0?`${LP.money(r)} / h`:'Tarif à configurer'}
    if(m===MODEL.GAME){const r=unitPrice(st,players);return r>0?`${LP.money(r)} / partie`:'Tarif à configurer'}
    if(m===MODEL.PLAYER_GAME){const r=unitPrice(st,players);return r>0?`${LP.money(r)} / partie`:'Tarif à configurer'}
    if(m===MODEL.BLOCK){const r=unitPrice(st,players);return r>0?`${LP.money(r)} / ${LP.duration(blockMinutes(st))}`:'Tarif à configurer'}